### ISSUE TITLE
not working on web

### ISSUE THREAD

**Issue by Fevzettin1** [alihassan143/htmltopdfwidgets#19]
I want to convert html to pdf in my flutter web project, but unfortunately the work in the example does not yield results.

Can you help with this?

**Comment by pramodkr123** [comment]
Are you getting any solution for the flutter web. I am unable to generate html to pdf in web.

**Comment by MGARockAByte** [comment]
I think it works on Flutter Web now. I'm running it with the current version. Have you tested it yet, @pramodkr123?

**Comment by pramodkr123** [comment]
Yes, I have tested it, but it doesn't work. Can you provide me with the code for the web version? @MGARockAByte

**Comment by MGARockAByte** [comment]
> Yes, I have tested it, but it doesn't work. Can you provide me with the code for the web version? @MGARockAByte

Sure 
main.dart:
```
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:htmltopdfwidgets/htmltopdfwidgets.dart' as html_to_pdf;

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'HTML to PDF Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  final String htmlString = '''
    <h1>Hello world</h1>

    <p>This is a paragraph with a word in <b>bold</b> followed by a break.<br>The text comes after the break.</p>

    <p>A list:</p>
    <ul>
        <li>Element 1</li>
        <li>Element 2</li>
        <li>Element 3</li>
    </ul>

    <p>follow <a href="https://www.example.com">link</a></p>
    ''';

  void _downloadPdf() async {
    final pdfData = await _generatePdf();

    await Printing.sharePdf(
      bytes: pdfData,
      filename: 'example.pdf',
    );
  }

  Future<Uint8List> _generatePdf() async {
    final pdf = pw.Document();
    var htmlWidgets = await html_to_pdf.HTMLToPdf().convert(htmlString);
    pdf.addPage(
      pw.MultiPage(
        build: (pw.Context context) => [
          pw.Column(children: htmlWidgets),
        ],
      ),
    );

    return pdf.save();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: _downloadPdf,
        child: const Text('Generate and download PDF'),
      ),
    );
  }
}
```
pubspec.yaml:
```
name: html_to_pdf_tester
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  htmltopdfwidgets: ^1.0.5
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
```
